services:
  mysql:
    image: mysql:8.0
    container_name: smartstay-db
    environment:
      MYSQL_ROOT_PASSWORD: DB_Password123!
      MYSQL_DATABASE: Smart_Hotel_v_1_0
    ports:
      - "3307:3306"
    volumes:
      - smartstay_data:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/main/resources/sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped

volumes:
  smartstay_data: