# Database connection (used by JavaFX app through JDBC)

spring.datasource.url=jdbc:mysql://localhost:3306/Smart_Hotel_v_1_0?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=mj23
spring.datasource.password=DB_Password123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional app-level settings (custom, for your JavaFX app)

app.name=SmartStay PMS
app.defaultCurrency=MAD
app.defaultLocale=fr_MA